### PR TITLE
Convert to Webpack Plugin

### PR DESCRIPTION
**Pull request by ericclemmons**
I _just_ found out about a similar project:
> https://github.com/renke/auto-install-webpack-plugin

From what I can gather, this may be a better solution than what this project is doing.

Let's see if I can work up an overview (please check this @renke!)

- `npm-install-loader`:
  - Is a `loader`, intended to be used during the processing of a JS file.
  - Because of this, it only has access to the `source`, `map`, and webpack configuration.
  - As such, it actually parses the AST to determine which dependencies need installation.
  - It operates **synchronously** via `child_process.spawnSync` to ensure the thread & build is blocked until installation completes & any other loaders (e.g. `eslint-loader`, `style`, etc.) take over.
  - Unknown how this would affect `.css` files (e.g. `import "~bootstrap"`), which was next on the punch list.
  - Plans to support all CLI flags (#3).
  - Because it operates per-file, if there are 10 missing dependencies in that single file, they're all installed at once.
  - How does this contrast with a plugin?

- `auto-install-webpack-plugin`:
  - Is a `plugin`, which means it has access to the compiler and a great deal more.
  - Hooks directly into the [module][1] resolver, meaning it can do an **async** installation.
  - Looks to hook into _all_ module resolution, including those of stylesheets.
  - Does it block the build?
  - Does it install one dependency at a time?
  - How does this contrast with a loader?

I'll await feedback, but my initial thoughts are to:

1. Complete any outstanding issues.
2. Test out & send a PR to `auto-install-webpack-plugin` for similar behavior.
3. Deprecate this project & link users to it instead.

Frankly, this was to scratch an itch and @renke's project didn't show up in my results, but I'm not a fan of competing for the sake of competing.

[1]: https://github.com/webpack/docs/wiki/plugins#modulerequest-request-async-waterfall

### CODE REVIEW

**Comment by ericclemmons** [comment]
Sweet, got it all working!  Been busy with work, but it's pretty legit.

Going to see if I can get loaders working as well (e.g. `babel-loader`)

**Comment by ericclemmons** [comment]
Alright, this is in the home stretch and **it's amazing**!  I have an example project with the basics (e.g. working Babel + Webpack build) and all JS & CSS dependencies (heck, even loaders!) install on demand.

- [ ] Rewrite tests.
- [ ] Rename repo.
- [ ] Record video.
- [ ] Update README.
- [ ] Bump version.
- [ ] Publish!

**Comment by bebraw** [comment]
@ericclemmons Poke me when you want a bit of PR for this. :+1:

**Comment by ericclemmons** [comment]
@bebraw Alright, this is about as done as it can be for now.

I'll record another video (none of the current ones were too my liking) tomorrow.

It's pretty darn incredible IMO having this stuff "just work" while you code.  Especially if you do:

1. `import express from "express";`
2. -S
3. `app.use(...).get(...).etc.`
4. `app.listen(3000)`

By the time you finish _using_ the dependency, it's already been installed, saved, & reloaded :)

**Comment by bebraw** [comment]
@ericclemmons Ok, I'll blast it once you merge the PR and publish a new version. :smile:

**Pull request merged**
